// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.7
// source: subpub.proto

package subpub_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PubSubV1_Subscribe_FullMethodName = "/subpub_v1.PubSubV1/Subscribe"
	PubSubV1_Publish_FullMethodName   = "/subpub_v1.PubSubV1/Publish"
)

// PubSubV1Client is the client API for PubSubV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PubSubV1Client interface {
	// Подписка (сервер отправляет поток событий)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// Публикация (классический запрос-ответ)
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type pubSubV1Client struct {
	cc grpc.ClientConnInterface
}

func NewPubSubV1Client(cc grpc.ClientConnInterface) PubSubV1Client {
	return &pubSubV1Client{cc}
}

func (c *pubSubV1Client) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PubSubV1_ServiceDesc.Streams[0], PubSubV1_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PubSubV1_SubscribeClient = grpc.ServerStreamingClient[Event]

func (c *pubSubV1Client) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PubSubV1_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PubSubV1Server is the server API for PubSubV1 service.
// All implementations must embed UnimplementedPubSubV1Server
// for forward compatibility.
type PubSubV1Server interface {
	// Подписка (сервер отправляет поток событий)
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error
	// Публикация (классический запрос-ответ)
	Publish(context.Context, *PublishRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPubSubV1Server()
}

// UnimplementedPubSubV1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPubSubV1Server struct{}

func (UnimplementedPubSubV1Server) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedPubSubV1Server) Publish(context.Context, *PublishRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedPubSubV1Server) mustEmbedUnimplementedPubSubV1Server() {}
func (UnimplementedPubSubV1Server) testEmbeddedByValue()                  {}

// UnsafePubSubV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PubSubV1Server will
// result in compilation errors.
type UnsafePubSubV1Server interface {
	mustEmbedUnimplementedPubSubV1Server()
}

func RegisterPubSubV1Server(s grpc.ServiceRegistrar, srv PubSubV1Server) {
	// If the following call pancis, it indicates UnimplementedPubSubV1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PubSubV1_ServiceDesc, srv)
}

func _PubSubV1_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PubSubV1Server).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PubSubV1_SubscribeServer = grpc.ServerStreamingServer[Event]

func _PubSubV1_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubV1Server).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PubSubV1_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubV1Server).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PubSubV1_ServiceDesc is the grpc.ServiceDesc for PubSubV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PubSubV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subpub_v1.PubSubV1",
	HandlerType: (*PubSubV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _PubSubV1_Publish_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _PubSubV1_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "subpub.proto",
}
